[project]
name = "competitive-py"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "gdown>=6.3.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
